FROM docker.io/library/busybox@sha256:73aaf090f3d85aa34ee199857f03fa3a95c8ede2ffd4cc2cdb5b94e566b11662
COPY --chmod=0444 .ciw-build-inputs/README.md /ciw-input/README.md
USER 65532:65532
ENTRYPOINT ["/bin/cat"]
CMD ["/ciw-input/README.md"]
